### PR TITLE
<Feature: Ingame UI Implementation>

### PR DESCRIPTION
**Pull request by empireboy**
Add Prefabs from UI elements
Add Prefabs to GameScene

### CODE REVIEW

**Comment by waffel183** [comment]
The Happiness image overlaps the zoom bar on maximized screen
image

**Comment by waffel183** [comment]
Also the green Home button does not change color when hovered over, don't know if this is intended.

**Review by waffel183 — CHANGES_REQUESTED** [review]
Happiness Icon does not scale properly when maximized, see image above

**Comment by empireboy** [comment]
> The Happiness image overlaps the zoom bar on maximized screen
> image

I just tested this and it looks like you have your resolution in the editor set to *Free Aspect*.
Can you try some other resolutions, these should all fit well. If you maximize it and it is set to *Free Aspect* it won't have any gray bars at the side, meaning that isn't accurate enough, it will be a little different when you make a build because the window will be higher so it should fit.

**Review by waffel183 — APPROVED** [review]

**Pull request merged**
